### ISSUE TITLE
Scroll orizzontale bug

### ISSUE THREAD

**Issue by michaelF7** [RiuHz/Acquarium_Monitoring#14]
Casualmente la pagina scrolla verso destra (forse anche sinistra), non dovrebbe farlo.

**Comment by RiuHz** [comment]
La pagina sembra non scrollare a sinistra, riesci a dare una situazione ripetibile?

**Comment by michaelF7** [comment]
Grabba il div del link di Facebook ad esempio e muovi il mouse verso destra.

**Comment by RiuHz** [comment]
![image](https://user-images.githubusercontent.com/73028528/209413748-90c5d331-ebc9-4f4e-9ef7-2e9e93f1e433.png)
