### ISSUE TITLE
Ditemi se questa favicon vi piace che magari la cambiamo. (L'ho trovata solo in png ma in questo caso non dovrebbe essere un problema)

### ISSUE THREAD

**Issue by michaelF7** [RiuHz/Acquarium_Monitoring#34]
![image](https://user-images.githubusercontent.com/73028953/209894143-6a17673e-dafb-45e1-943d-008c54e4c8b2.png)

**Comment by Amedeo26** [comment]
Si è carina

**Comment by RiuHz** [comment]
LGTM, ma penso che essendo un progetto relativo alla scuola ci stia meglio quella della scuola
