### ISSUE TITLE
Creazione funzione per stoppare/avviare la stream + cambio icona.

### ISSUE THREAD

**Issue by michaelF7** [RiuHz/Acquarium_Monitoring#35]
Bisogna creare una funzione (Js) che vada ad implementare l'avvio e lo stop della live stream con relativo cambio di icona con queste modalità:

1. Se cliccata l'icona Pause la stream si stopperà (di base la stream sarà avviata grazie all'autoplay), l'icona cambierà con l'icona Play;
2. Se cliccata l'icona Play la stream si avvierà, l'icona cambierà con l'icona Pause;
3. Creare una funzione che permetta il cambio di icona;
4. Se il "div-per-stream" sarà cliccato una volta la stream si stopperà se verrà ri-cliccato la stream si avvierà, le icone dovranno cambiare di conseguenza;

Se ne dovranno occupare: 
- @G7-TRRS  per il css.
- @Amedeo26  per HTML.
- @G7-TRRS  o @Amedeo26  per Javascript.

**Comment by Amedeo26** [comment]
@michaelF7 Ho aggiunto l'icona e la funzione

**Comment by RiuHz** [comment]
Per il progetto finale si userà il tag video.
