### ISSUE TITLE
Bug "div-per-stream" + icona, andando a cliccare due volte l'icona play/pause il video va in fullscreen.

### ISSUE THREAD

**Issue by michaelF7** [RiuHz/Acquarium_Monitoring#37]
Quando si clicca l'icona pause due volte il video va in full screen probabilmente perché viene cliccato anche il "div-per-stream".

**Comment by michaelF7** [comment]
Una possibile soluzione potrebbe essere quella di aggiungere un secondo div nella parte inferiore del "div-per-stream" (trasparente in modo da poter comunque poter vedere il video al di sotto del div) in modo da evitare la possibilità di attivare il full screen anche con altre icone o cliccando vicino ad esse.

**Comment by michaelF7** [comment]
Se siete d'accordo appena possibile io oppure @Amedeo26 aggiungiamo il div (chiamato: "div-overlay") e @RiuHz  oppure @G7-TRRS  lo renderanno trasparente e lo posizioneranno nella parte inferiore del "div-per-stream"

**Comment by Amedeo26** [comment]
Risolto senza creare il div

**Comment by RiuHz** [comment]
> Se siete d'accordo appena possibile io oppure @Amedeo26 aggiungiamo il div (chiamato: "div-overlay") e @RiuHz  oppure @G7-TRRS  lo renderanno trasparente e lo posizioneranno nella parte inferiore del "div-per-stream". Il "div-overlay" conterrà tutte le icone. 

Esiste già, se non erro è chiamato div live e basta rinominare la classe in html e css.

**Comment by RiuHz** [comment]
> Una possibile soluzione potrebbe essere quella di aggiungere un secondo div nella parte inferiore del "div-per-stream" (trasparente in modo da poter comunque vedere il video al di sotto del div) in modo da evitare la possibilità di attivare il full screen anche con altre icone o cliccando vicino ad esse. 

Provate a aggiungere all'icona in questione la stessa funzione sia onclick che ondbclick, dovrebbe risolversi

**Comment by michaelF7** [comment]
> > Una possibile soluzione potrebbe essere quella di aggiungere un secondo div nella parte inferiore del "div-per-stream" (trasparente in modo da poter comunque vedere il video al di sotto del div) in modo da evitare la possibilità di attivare il full screen anche con altre icone o cliccando vicino ad esse.
> 
> Provate a aggiungere all'icona in questione la stessa funzione sia onclick che ondbclick, dovrebbe risolversi

Non sembra funzionare.

**Comment by RiuHz** [comment]
Risolto, ho semplicemente evitato che l'event 'dblclick' innescato sull'icona play / pause non fosse poi passato al div parent.

**Comment by michaelF7** [comment]
Ho risolto il problema utilizzando l'attributo z-index (CSS), praticamente ho aumentato la quota del "div-overlay" ad 1 e ho impostato la quota della "stream" (l'iframe) a 0 in questo modo il "div-overlay" sarà al di sopra dell'iframe, quindi non sarà possibile cliccare l'iframe quando si vorrà cliccare le icone evitando eventi indesiderati (Es. in precedenza quando si cliccava due volte su un'icona si attivava il fullscreen).
