### ISSUE TITLE
Modifica footer.

### ISSUE THREAD

**Issue by michaelF7** [RiuHz/Acquarium_Monitoring#41]
Il footer andrebbe modificato gli elementi dovrebbero essere suddivisi per categoria:

- Informazioni Ferraris, che comprenderà email, pec ecc (In questa sezione potremmo aggiungere anche il numero di telefono della scuola o segreteria non so come funziona);
- Classi coinvolte (Oppure qualcosa del genere);
- Quella già esistente "Hanno lavorato al progetto".

I titoli di lista potremmo farli in bold oppure potremmo utilizzare "Aquatico" come font per diversificarli, inoltre ciascun elemento delle liste dovrebbe essere allineato al di sotto della prima lettera del titolo della lista.

**Comment by RiuHz** [comment]
<img src='https://user-images.githubusercontent.com/73028528/209413748-90c5d331-ebc9-4f4e-9ef7-2e9e93f1e433.png'>
